#!/usr/bin/env python3

import argparse
import logging

_logger = logging.getLogger(__name__)

_monotime="""\
static inline double monotime()
{
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC,&ts);
    return ts.tv_sec + 1e-9*ts.tv_nsec;
}
"""

_catch="""\
catch (const std::exception& exc)
{
}
"""

def main():
    parser = argparse.ArgumentParser("Generate C++ boilerplate")
    parser.add_argument("-m","--monotime",action="store_true",default=False)
    parser.add_argument("-c","--catch",action="store_true",default=False)
    args = parser.parse_args()

    if args.monotime:
        print(_monotime)
    if args.catch:
        print(_catch)

if __name__ == "__main__":
    main()
