#!/bin/sh
cat <<EOF
#!/usr/bin/env python3

import argparse
import logging

_logger = logging.getLogger(__name__)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(dest="filename")
    parser.add_argument("--debug",action="count",default=0)
    opts = parser.parse_args()

    logging.basicConfig( level=logging.INFO )
    if opts.debug:
        _logger.setLevel(logging.DEBUG)
        _logger.debug("debug level {0}".format(opts.debug))
        if opts.debug > 1:
            logging.getLogger("").setLevel(logging.DEBUG)

if __name__ == "__main__":
    main()
EOF
